#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import argparse
import code_extract


def _main():
    args = _parse_cmd_arguments()
    code_blocks = code_extract.extract(args.infile, filter=args.filter)
    code_extract.write(code_blocks, args.outfile)
    return


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Extract code blocks from markdown files.'
        )
    parser.add_argument(
            'infile',
            type=str,
            help='input markdown file'
            )
    parser.add_argument(
            'outfile',
            type=str,
            help='output code file'
            )
    parser.add_argument(
            '-f', '--filter',
            type=str,
            help='filter string',
            default=None,
            )
    return parser.parse_args()


if __name__ == '__main__':
    _main()
