#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import argparse
import sys

# pylint: disable=import-self
import excode


def _main():
    args = _parse_cmd_arguments()

    if args.add_code:
        args.outfile.write(args.add_code)

    code_blocks = excode.extract(args.infile, filter=args.filter)
    excode.write(args.outfile, code_blocks)
    return


def _parse_cmd_arguments():
    parser = argparse.ArgumentParser(
        description='Extract code blocks from markdown files.'
        )
    parser.add_argument(
        'infile',
        type=argparse.FileType('r'),
        default=sys.stdin,
        help='input markdown file'
        )
    parser.add_argument(
        'outfile',
        type=argparse.FileType('w'),
        default=sys.stdout,
        help='output file'
        )
    parser.add_argument(
        '-f', '--filter',
        type=str,
        help='filter string',
        default=None,
        )
    parser.add_argument(
        '-a', '--add-code',
        type=str,
        help='add code to the beginning of the output file',
        default=None,
        )
    return parser.parse_args()


if __name__ == '__main__':
    _main()
