name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: pre-commit/action@v3.0.0

  build:
    needs: [lint]

    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - platform: macos-latest
            python-version: "3.10"
          - platform: windows-latest
            python-version: "3.10"

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov pytest_codeblocks --cov-report xml --cov-report term
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
